#!/bin/bash

## update packages
sudo apt-get update
sudo apt-get upgrade

# install mongo
sudo apt-get install -y mongodb-server
# start service and open mongo shell
sudo service mongodb start
# create db and collection
mongo 663 --eval 'db.createCollection("rooms")'

# install nodejs/npm
sudo apt-get install -y nodejs
# install project packages
npm install